#name: dfpl_env_cd
#channels:
#  - conda-forge
#  - defaults
#dependencies:
#  # dev requirements
#  - conda-build>=3.21.8
#  - conda>=4.12.0
#  - pip>=22.0.4
#  - pytest>=7.1.1
#  # application requirements
#  - protobuf==3.20.3
#  - jsonpickle>=2.1
#  - matplotlib>=3.5.1
#  - numpy>=1.22.2
#  - pandas>=1.4.2
#  - rdkit>=2022.03.1
#  - scikit-learn>=1.0.2
#  - seaborn>=0.12.2
#  - tensorflow>=2.13
#  - wandb>=0.16.2
#  - umap-learn>=0.5.3
#  - pip:
#    - git+https://github.com/soulios/chemprop.git@1d73523e49aa28a90b74edc04aaf45d7e124e338
#
name: dfpl_env_cd
channels:
  - conda-forge
  - defaults
dependencies:
  # dev requirements
  - conda-build>=3.21.8
  - conda>=4.12.0
  - pip>=22.0.4
  - pytest>=7.1.1
  # application requirements
  - protobuf>=3.21.12
  - jsonpickle>=2.1
  - matplotlib>=3.5.1
  - numpy>=1.22.2
  - rdkit>=2023.03.3
  - scikit-learn>=1.0.2
  - seaborn>=0.12.2
  - tensorflow>=2.13
  - wandb>=0.16.2
  - umap-learn>=0.5.3
  - pip:
    - git+https://github.com/soulios/chemprop.git@cfcb67a

